language: python

# command to install dependencies
install:
  - sudo apt-get update
  # Get the newest mini conda and install anaconda.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

  # installing anaconda
  - conda install anaconda

  # install project dependency
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

script:
  # Test for python static analysis with flake8 and pydocstyle.
  - flake8
  - pydocstyle
